l_english:
 MOD_ARTIFACT_DECAY_REDUCTION_ADD:0 "Зниження руйнування артефакту"
 MOD_ARTIFACT_DECAY_REDUCTION_MULT:0 "$MOD_ARTIFACT_DECAY_REDUCTION_ADD$"

 artifact_history_created_title:1 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_created_desc:2 "Творець: [SelectLocalization( HISTORY_ENTRY.HasActor, HISTORY_ENTRY.GetActor.GetNameNoTooltip, 'UNKNOWN_BENEFACTOR' )]\nСтворено для:[HISTORY_ENTRY.GetReit
 artifact_history_stolen_title:1 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_stolen_desc:3 "Викрадено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_created_before_history_title:0 "Створення невідомо"
 artifact_history_created_before_history_desc:0 "Подробиці створення цього артефакту невідомі"
 artifact_history_given_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_given_desc:1 "Подаровано персонажу [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_inherited_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_inherited_desc:1 "Успадковано персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_conquest_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_conquest_desc:2 "Захоплено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] у війні проти персонажа [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_siege_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_siege_desc:1 "Захоплено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] після облоги володіння [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_reforged_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_reforged_desc:1 "Об'єднано персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] з провінції [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"
 artifact_history_discovered_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_discovered_desc:2 "Відкрито персонажем [HISTORY_ENTRY.GetActor.GetTitledFirstNameNicknamedNoTooltipRegnal] за дорученням персонажа [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]
 artifact_history_claimed_by_house_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_claimed_by_house_desc:2 "Заперечується [Concept( 'house', 'домом' )|E] [HISTORY_ENTRY.GetActor.GetHouse.GetNameNoTooltip]"
 artifact_history_won_in_duel_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_won_in_duel_desc:1 "Виграно у поєдинку проти персонажа [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal]"
 artifact_history_taken_in_battle_title:0 "[HISTORY_ENTRY.GetDate.GetString]"
 artifact_history_taken_in_battle_desc:1 "Захоплено персонажем [HISTORY_ENTRY.GetRecipient.GetTitledFirstNameNicknamedNoTooltipRegnal] під час битви в провінції [HISTORY_ENTRY.GetLocation.GetNameNoTooltip]"

 UNKNOWN_BENEFACTOR:0 "невідомий благодійник"

 ARTIFACT_DURABILITY:0 "Міцність: $CURRENT|1$ / $MAX|1$"
 ARTIFACT_HISTORY:0 "Історія артефакту"

 crown:0 "Вінець"
 helmet:0 "Головний убір"
 miscellaneous:0 "$trinket$"
 miscellaneous_when_not_court:0 "$trinket$"
 regalia:0 "Регалія"
 weapon:0 "Зброя"
 primary_armament:0 "$weapon$"
 armor:0 "Зброя"
 trinket:0 "Прикраса"
 trinket_1:0 "$trinket$"
 trinket_2:0 "$trinket$"
 trinket_3:0 "$trinket$"
 trinket_4:0 "$trinket$"

 # Names for the artifact that are placed in the slot
 artifact_slot_pedestal:1 "Предмет для п'єдесталу"
 artifact_slot_helmet:0 "Головний убір"
 artifact_slot_miscellaneous:0 "Прикраса"
 artifact_miscellaneous_when_not_court:0 "$miscellaneous_when_not_court$"
 artifact_slot_armor:0 "Зброя"
 artifact_slot_sculpture:0 "Меблі"
 artifact_slot_primary_armament:0 "Зброя"
 artifact_slot_throne:0 "Трон"
 artifact_slot_wall_big:0 "Великий настінний орнамент"
 artifact_slot_regalia:0 "Регалії"
 artifact_slot_wall_small:0 "Малий настінний орнамент"
 artifact_slot_book:0 "Книга"

 artifact_crown:0 "Корона"
 artifact_helmet:0 "Головний убір"
 artifact_miscellaneous:0 "$trinket$"
 artifact_regalia:0 "Регалії"
 artifact_regalia_simple:0 "$regalia$"
 artifact_armor:0 "Зброя"
 artifact_trinket:0 "Прикраса"
 artifact_pedestal:0 "Предмет для п'єдесталу"
 artifact_wall_big:0 "Великий настінний орнамент"
 artifact_tapestry:0 "Гобелен"
 artifact_sculpture:0 "Меблі"
 artifact_scientific_apparatus:0 "Науковий прилад"
 artifact_wall_small:0 "Малий настінний орнамент"
 artifact_animal_skull:0 "Череп тварини"
 artifact_animal_hide:0 "Шкура тварини"
 artifact_animal_hide_big:0 "Велика шкура тварини"
 artifact_throne:0 "Трон"
 artifact_box:0 "Скринька"
 artifact_goblet:0 "Кубок"
 artifact_jug:0 "Глечик"
 artifact_book:0 "Книга"
 artifact_panacea:0 "Панацея"
 artifact_elixir:0 "Еліксір"
 artifact_philosophers_stone:0 "Філософський камінь"
 # These keys all use $weapon$ because despite being unique types, вони all go in the weapon slot
 artifact_sword:1 "меч"
 artifact_axe:1 "$axe$"
 artifact_spear:1 "$spear$"
 artifact_hammer:1 "$hammer$"
 artifact_dagger:1 "$dagger$"
 artifact_mace:1 "$mace$"
 # Same as the above, but for armor types
 artifact_armor_mail:0 "$armor$"
 artifact_armor_plate:0 "$armor$"
 artifact_armor_scale:0 "$armor$"
 artifact_armor_lamellar:0 "$armor$"
 artifact_armor_laminar:0 "$armor$"
 artifact_armor_brigandine:0 "$armor$"


 pedestal:2 "П'єдестал"
 wall_big:0 "Великий настінний орнамент"
 wall_small:0 "Малий настінний орнамент"
 sculpture:1 "Меблі"
 throne:0 "Трон"
 book:0 "Книга"

 wall_big_1:0 "$wall_big$"
 wall_big_2:0 "$wall_big$"
 wall_big_3:0 "$wall_big$"
 wall_small_1:0 "$wall_small$"
 wall_small_2:0 "$wall_small$"
 wall_small_3:0 "$wall_small$"
 sculpture_1:0 "$sculpture$"
 sculpture_2:0 "$sculpture$"
 lectern_1:0 "$book$"
 lectern_2:0 "$book$"
 lectern_3:0 "$book$"
 pedestal_1:0 "$pedestal$"
 pedestal_2:0 "$pedestal$"
 pedestal_3:0 "$pedestal$"
 pedestal_4:0 "$pedestal$"

#rarity levels
 common:2 "Звичайний"
 masterwork:0 "Майстерня"
 famed:0 "Знаменитий"
 illustrious:0 "Чудовий"
 
#old rarity levels (unused?)
 legendary:0 "Легендарний"
 rare:0 "Рідкісний"

 REFORGE_ARTIFACT_TITLE:0 "Перекувати артефакт"
 REFORGE:0 "Перекувати"
 REFORGE_ARTIFACT:0 "#T $REFORGE_ARTIFACT_TITLE$#!"
 REPAIR_ARTIFACT_TITLE:0 "Починати артефакт"
 REPAIR:0 "Полагодити"
 REPAIR_ARTIFACT:0 "#T $REPAIR_ARTIFACT_TITLE$#!"
 EFFECTS_ON_ARTIFACT:0 "Ефекти на артефакті "[Artifact.GetName]""
 CHARACTER_PAYS_REFORGE_COST:0 "[CHARACTER.GetNamePossessiveOrMy|U][Select_CString(CHARACTER.IsPlayer, ' персонаж', '' )] заплатить $COST$, щоб перекувати артефакт «[ARTIFACT.GetName]»"
 CHARACTER_PAYS_REPAIR_COST:0 "[CHARACTER.GetNamePossessiveOrMy|U][Select_CString(CHARACTER.IsPlayer, ' персонаж', '' )] заплатить $COST$, щоб полагодити артефакт «[ARTIFACT.GetName]»"
 ARTIFACT_CHANGES_NAME:0 "Артефакт "[ARTIFACT.GetName]" тепер буде називатися "$NEW_NAME$""
 ARTIFACT_CHANGES_DESC:0 "Зміниться опис артефакту «[ARTIFACT.GetName]»"
 ARTIFACT_CHANGES_VISUALS:0 "[ARTIFACT.GetName] зовні зміниться"
 ARTIFACT_CHANGES_TYPE:0 "Артефакт "[ARTIFACT.GetName]" змінить тип на $NEW_TYPE$"
 ARTIFACT_CHANGES_RARITY:0 "Рідкість артефакту [ARTIFACT.GetName]" зміниться на $NEW_RARITY$"
 ARTIFACT_CHANGES_MODIFIER:1 "Артефакт «[ARTIFACT.GetName]» надасть наступні бонуси:\n$NEW_MODIFIER$"
 ARTIFACT_CHANGES_TEMPLATE:0 "Артефакт "[ARTIFACT.GetName]" стане $NEW_TEMPLATE$"
 ARTIFACT_CHANGES_DURABILITY:0 "Міцність артефакту "[ARTIFACT.GetName]" зміниться на $NEW_DURABILITY$ / $MAX_DURABILITY$"
 ARTIFACT_FULLY_REPAIRED:0 "Артефакт "[ARTIFACT.GetName]" буде повністю відновлений"
 NEW_ARTIFACT_TOOLTIP:0 "Це новий [Concept( 'artifact', 'артефакт' )|E]"
 ARTIFACT_RARITY_AND_TYPE:0 "[ARTIFACT.GetType] ([ARTIFACT.GetRarity] артефакт)"
 ARTIFACT_TYPE_ONLY:0 "[ARTIFACT.GetType]"
 ARTIFACT_RARITY_AND_SLOT_TYPE:0 "[ARTIFACT.GetSlotType] ([ARTIFACT.GetRarity] артефакт)"
 ARTIFACT_SLOT_TYPE_ONLY:0 "[ARTIFACT.GetSlotType]"
 INVENTORY_ARTIFACTS_SINGLE:0 "[inventory_artifact|E]"
 RENAME_ARTIFACT:0 "#T Перейменувати артефакт#!"
 RENAME_ARTIFACT_TITLE:1 "Перейменувати [ARTIFACT.GetNameNoTooltip]"
 RENAME_ARTIFACT_DESC:1 "Змінити назву артефакту "[ARTIFACT.GetNameNoTooltip]""
 RENAME_ARTIFACT_ACCEPT:0 "Прийняти"
 ARTIFACT_CURRENT_HOLDER:0 "Поточний власник: [Artifact.GetOwner.GetName]"
 DETAILS_TAB_HISTORY:0 "Історія"
 DETAILS_TAB_CLAIMS:1 "Претенденти"
 DETAILS_TAB_CLAIM_INTERACTIONS:0 "У вас є претензія"
 DETAILS_TAB_NO_CLAIMANTS:0 "Ні у кого немає [Concept( 'artifact_claim', 'претензій' )|E] на цей [Concept( 'artifact', 'артефакт' )|E]"
 CHARACTER_HAS_NO_ARTIFACTS:1 "Немає [Concept( 'artifacts', 'артефактів' )|E]"
 CHARACTER_HAS_NO_CLAIMED_ARTIFACTS:2 "[artifact_claims|E] відсутні"
 ARTIFACT_DETAILS_TITLE:0 "Відомості про артефакт"
 ARTIFACT_DETAILS:0 "#T $ARTIFACT_DETAILS_TITLE$#!"
 ARTIFACT_SORTING_ALL_BUTTON:0 "Всі"
 created:0 "Створено"
 reforged:0 "Перекований"
 given:0 "Отдан"
 stolen:0 "Украден"
 conquest:0 "Завойований"
 created_before_history:0 "Невідомого походження"
 inherited:0 "Успадкований"
 discovered:0 "Відкритий"
 taken_in_siege:0 "В облозі"
 won_in_duel:0 "Виграно у поєдинку"
 taken_in_battle:0 "Захоплено у битві"
 CLAIMANT_ENTRY_HOUSE_HEAD:0 "Глава будинку: [ClaimantEntry.GetHouse.GetHeadOfHouse.GetName]"
 ARTIFACT_YEARS_UNTIL_DECAY:0 "[Artifact.GetYearsUntilDecay] років"
 ARTIFACT_DURABILITY_TOOLTIP:1 "#T Міцність#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nПри нинішній швидкості руйнування цей [Concept( 'artifact', 'артефакт' )|E] прослужить [ARTIFACT. GetYearsUntilDecay] років, перш ніж у нього закінчиться [Concept( 'durability', 'міцність' )|E] і він зламається."
 ARTIFACT_DURABILITY_NO_DECAY_TOOLTIP:1 "#T Міцність#!\n#V $DURABILITY|1$ / $MAX_DURABILITY|1$#!\nВ даний момент цей [Concept( 'artifact', 'артефакт' )|E] не руйнується і прослужить скільки завгодно довго, якщо не почне втрачати [Concept( 'durability', 'міцність' )|E ]."
 DECAY_TOTAL:0 "Щорічна руйнація"
 DECAY_BASE:0 "Базова руйнація"
 CHARACTER_HAS_NO_VALID_SLOT:1 "@warning_icon!#X Немає осередків для зберігання артефакту «[ARTIFACT.GetName]»#!"
 SLOT_CANNOT_HOLD_ARTIFACT:0 "@warning_icon!#X $SLOT$ не підходить для зберігання артефактів типу «$TYPE$»#!"
 EQUIP_ARTIFACT:4 "\n#I Натисніть, щоб взяти артефакт#!"
 UNEQUIP_QUICK_TT:0 "#T Зняти#!"
 EQUIP_ARTIFACT_REPLACE:0 "\n#I Клацніть, щоб замінити артефакт «$REPLACE_ARTIFACT$» на цей #!"
 SELECT_ARTIFACT:0 "Вибрати артефакт"
 ARTIFACT_ALREADY_EQUIPPED_IN_SLOT:1 "@warning_icon!#X Артефакт «[ARTIFACT.GetNameNoTooltip]» вже знаходиться в цьому осередку#!"
 INVENTORY_SLOT_TT:0 "#T Осередок «[InventorySlot.GetName]»\n#![SelectLocalization( InventoryView.IsSelectedSlot( InventorySlot.Self ), 'SELECT_ARTIFACT_FOR_SLOT', 'SELECT_INVENTORY_SLOT')
 SELECT_INVENTORY_SLOT:1 "#I Клацніть, щоб показати артефакт «[InventorySlot.GetName]»#!"
 SELECT_ARTIFACT_FOR_SLOT:1 "#I Клацніть, щоб зняти виділення#!"
 CHARACTER_CANNOT_DECLARE_WAR:0 "[Character.GetShortUINameNoTooltip|U] не може розпочати війну за цей [Concept( 'artifact', 'артефакт' )|E]"
 CHARACTER_CANNOT_DECLARE_WAR_SHORT:0 "Неможливо оголосити війну"
 CHARACTER_CAN_DECLARE_WAR:0 "[Character.GetShortUINameNoTooltip|U] може почати війну за цей [Concept( 'artifact', 'артефакт' )|E]"
 #DECLARE_WAR_FOR_ARTIFACT_TOOLTIP:0 "#T Declare War for Artifact#!" #<DELETE THIS KEY>
 DUEL_FOR_ARTIFACT_TOOLTIP:0 "#T Поєдинок за артефакт#!"
 ARTIFACT_SORT_ORDER_TOOLTIP:0 "#T Змінити порядок сортування артефактів#!"
 ARTIFACT_CLAIM_SORT_ORDER_TOOLTIP:0 "#T [artifact_claim|e]: змінити порядок сортування#!"
 ARTIFACT_SORTING_TAB_TOOLTIP:1 "[InventorySlotType.GetName] [artifacts|el]"
 ARTIFACT_SORTING_TAB_ALL_TOOLTIP:1 "Всі [claimants|El]"
 acquisition_date:0 "Дата отримання"
 creation_date:0 "Дата створення"
 type:0 "Тип"
 rarity:0 "Рідкість"
 name:0 "Назва"
 durability:0 "Міцність"
 artifact_type:0 "Тип артефакту"
 claim_type:0 "Тип претензії"
 UNEQUIP_ARTIFACT:2 "\n#I Клацніть, щоб забрати артефакт#!"
 ARTIFACT_EQUIPPED_TOOLTIP:0 "#T [artifact|e] взятий#!"
 ARTIFACT_AT_MAX_DURABILITY:0 "@warning_icon!#X Артефакт «[ARTIFACT.GetNameNoTooltip]» вже має максимальну міцність#!"
 IMMINENT_HOUSE_CLAIMANT:0 "[Artifact.GetOwner.GetHouse.GetName] #low ([Artifact.GetYearsUntilHouseClaim( Artifact.GetOwner.Self )] років)#!"
 HOUSE_CLAIMS:0 "#help Претензії дому:#!"
 DECAY_ARTIFACT_EQUIPPED:0 "Взято"
 DECAY_ARTIFACT_DISPlAY:0 "Виставлено"
 DECAY_ARTIFACT_UNEQUIPPED:0 "У сховищі"
 DISPLAY_ARTIFACT:0 "#I \nКлацніть, щоб виставити#!"
 PUT_COURT_ARTIFACT_ON_DISPLAY:3 "#I \nКлацніть, щоб виставити тут#!"
 REMOVE_COURT_ARTIFACT_FROM_DISPLAY:3 "#I \nКлацніть, щоб прибрати в сховище#!"
 MOVE_COURT_ARTIFACT_TO_DISPLAY:2 "#I \nКлацніть, щоб перемістити сюди#!"
 COURT_ARTIFACT_ON_DISPLAY:0 "#T [court_artifact|e] виставлено на показ#!"
 ROYAL_COURT:0 "Монарший двір"
 ARTIFACT_STORAGE:1 "Придворні артефакти"
 ARTIFACT_CLAIMS:0 "Претензії на артефакти"
 NEW_ARTIFACT:1 "#V Новий#!"
 EQUIPPED_ARTIFACT:2 "[Select_CString( Artifact.IsCourtArtifact, 'Демонструється', 'Використовується' )] [Inventory.GetEquippedSlotOfMaxSlotText( Artifact.Self ]]"
 CHARACTER_WITHOUT_ROYAL_COURT_COURT_ARTIFACT_TAB:1 "Оскільки [Character.GetShortUIName] не [Character.LocalPlayerString( 'маю', 'має' )] [Concept( 'royal_court', 'mor'C[ .LocalPlayerString( 'можу', 'може' )] виставити цей [court_artifact|el] на огляд."
 ARTIFACT_TITLE_ASSOCIATION:1 "Успадковано разом з титулом «[Artifact.GetAssociatedTitle.GetNameWithUnderlying]»"
 EMPTY_INVENTORY_TOOLTIP:0 "@warning_icon!#X Не можна переглянути інвентар: ні [Concept( 'artifacts', 'артефактів' )|E] або [Concept( 'artifact_claims', 'претензій на артефакти' )#E" для демонстрації
 ARTIFACT_PERSONAL_CLAIM:0 "Особиста претензія"
 ARTIFACT_HOUSE_CLAIM:0 "Претензія вдома"
 REFORGE_ARTIFACT_COMPLETELY:1 "Перекласти артефакт «[ARTIFACT.GetNameNoTooltip]» у тип «$NEW_TYPE$»"
 REFORGE_COST:1 "Вартість перековування: $COST$"
 REPAIR_COST:0 "Вартість ремонту : $COST$"
 CANNOT_REFORGE_WITHOUT_ANTIQUARIAN:0 "@warning_icon!#X Не можна перекувати [artifacts|el], тому що у вас немає $antiquarian_court_position$#!"
 ARTIFACT_FALLBACK_EFFECT:1 "#S Якщо ви не відповідаєте вимогам:#!\n[Artifact.GetFallbackEffects]"
 ARTIFACT_EFFECT:0 "[SelectLocalization( Artifact.HasCanBenefit, 'ARTIFACT_EFFECT_HAS_CAN_BENEFIT', '' )][Artifact.GetModifierEffects]"
 ARTIFACT_EFFECT_HAS_CAN_BENEFIT:0 "#S Якщо ви відповідаєте #TOOLTIP:ARTIFACT_EFFECT_REQUIREMENT_TT #L вимогам#!#!:#!\n"
 ARTIFACT_EFFECT_REQUIREMENT_TT:0 "[Artifact.GetCanBenefitPlayerDesc]"